(() => {
  'use strict';

  const DB_KEY = 'spaflow_static_db_v1';
  const SESSION_KEY = 'spaflow_static_session_v1';
  const APP = document.getElementById('app');
  const MODAL = document.getElementById('modalRoot');
  const TOASTS = document.getElementById('toastRegion');

  const ICONS = {
    home:'<path d="M3 11.5 12 4l9 7.5"/><path d="M5.5 10.5V20h13v-9.5"/><path d="M9.5 20v-6h5v6"/>',
    calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',
    plus:'<path d="M12 5v14M5 12h14"/>',
    users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',
    heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.6l-1-1a5.5 5.5 0 0 0-7.8 7.8l1 1L12 21l7.8-7.6 1-1a5.5 5.5 0 0 0 0-7.8Z"/>',
    package:'<path d="m21 8-9 5-9-5 9-5 9 5Z"/><path d="m3 8 9 5 9-5M3 8v8l9 5 9-5V8M12 13v8"/>',
    chart:'<path d="M3 3v18h18"/><path d="m7 16 4-5 4 3 5-7"/>',
    settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21h-4v-.08A1.7 1.7 0 0 0 9 19.36a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.63 15 1.7 1.7 0 0 0 3.08 14H3v-4h.08A1.7 1.7 0 0 0 4.64 9a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.63 1.7 1.7 0 0 0 10 3.08V3h4v.08A1.7 1.7 0 0 0 15 4.64a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.37 9 1.7 1.7 0 0 0 20.92 10H21v4h-.08A1.7 1.7 0 0 0 19.4 15Z"/>',
    logout:'<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><path d="m16 17 5-5-5-5M21 12H9"/>',
    menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',
    money:'<circle cx="12" cy="12" r="9"/><path d="M16 8h-6a2 2 0 0 0 0 4h4a2 2 0 0 1 0 4H8M12 6v12"/>',
    search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',
    edit:'<path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L8 18l-4 1 1-4Z"/>',
    trash:'<path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6M10 11v6M14 11v6"/>',
    check:'<path d="m5 12 4 4L19 6"/>',
    x:'<path d="m6 6 12 12M18 6 6 18"/>',
    card:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18"/>',
    gift:'<path d="M20 12v9H4v-9M2 7h20v5H2zM12 7v14"/><path d="M12 7H7.5A2.5 2.5 0 1 1 10 4.5C10 7 12 7 12 7ZM12 7h4.5A2.5 2.5 0 1 0 14 4.5C14 7 12 7 12 7Z"/>',
    tag:'<path d="M20.6 13.6 13.6 20.6a2 2 0 0 1-2.8 0L3.4 13.2a2 2 0 0 1-.6-1.4V4a1 1 0 0 1 1-1h7.8a2 2 0 0 1 1.4.6l7.6 7.2a2 2 0 0 1 0 2.8Z"/><circle cx="8.5" cy="8.5" r="1.5"/>',
    receipt:'<path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6M9 12h6"/>',
    shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>',
    download:'<path d="M12 3v12M7 10l5 5 5-5"/><path d="M5 21h14"/>',
    upload:'<path d="M12 21V9M7 14l5-5 5 5"/><path d="M5 3h14"/>',
    clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
    building:'<path d="M4 21V4h11v17M15 9h5v12M8 8h3M8 12h3M8 16h3M3 21h18"/>'
  };

  const icon = (name, cls='') => `<svg class="icon ${cls}" viewBox="0 0 24 24" aria-hidden="true">${ICONS[name] || ICONS.heart}</svg>`;
  const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const clone = o => JSON.parse(JSON.stringify(o));
  const pad = n => String(n).padStart(2,'0');
  const todayISO = () => { const d=new Date(); return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`; };
  const dateTimeLocal = (d=new Date()) => `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
  const toDate = value => value ? new Date(value) : null;
  const fmtDate = value => { if(!value) return '—'; const v=String(value); const d=/^\d{4}-\d{2}-\d{2}$/.test(v)?new Date(v+'T12:00:00'):new Date(v); return new Intl.DateTimeFormat('es-BO',{day:'2-digit',month:'2-digit',year:'numeric'}).format(d); };
  const fmtDateTime = value => value ? new Intl.DateTimeFormat('es-BO',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value)) : '—';
  const fmtTime = value => value ? new Intl.DateTimeFormat('es-BO',{hour:'2-digit',minute:'2-digit'}).format(new Date(value)) : '—';
  const money = value => `Bs ${Number(value||0).toLocaleString('es-BO',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  const byId = (arr,id) => arr.find(x => String(x.id) === String(id));
  const nextId = arr => (arr.length ? Math.max(...arr.map(x => Number(x.id)||0)) : 0) + 1;
  const isSameDay = (a,b) => a && b && new Date(a).toDateString() === new Date(b).toDateString();
  const startOfDay = d => { const x=new Date(d); x.setHours(0,0,0,0); return x; };
  const endOfDay = d => { const x=new Date(d); x.setHours(23,59,59,999); return x; };
  const debounce = (fn, wait=180) => { let t; return (...args)=>{ clearTimeout(t); t=setTimeout(()=>fn(...args),wait); }; };

  let db = null;
  let currentView = 'dashboard';
  let sidebarOpen = false;

  function resolveRelative(value){
    if(typeof value !== 'string' || !value.startsWith('$TODAY')) return value;
    const m = value.match(/^\$TODAY([+-]\d+)?(T\d{2}:\d{2})?$/);
    if(!m) return value;
    const d = new Date(); d.setHours(0,0,0,0); d.setDate(d.getDate() + Number(m[1]||0));
    if(m[2]){ const [h,min] = m[2].slice(1).split(':').map(Number); d.setHours(h,min,0,0); return dateTimeLocal(d); }
    return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
  }
  function resolveDeep(obj){
    if(Array.isArray(obj)) return obj.map(resolveDeep);
    if(obj && typeof obj === 'object') return Object.fromEntries(Object.entries(obj).map(([k,v])=>[k,resolveDeep(v)]));
    return resolveRelative(obj);
  }

  function buildSeed(source=window.SPAFLOW_SEED || {}){
    const s = resolveDeep(clone(source));
    return {
      meta:{version:1,initializedAt:new Date().toISOString()},
      business:s.business?.business || {}, branches:s.business?.branches || [], rooms:s.business?.rooms || [],
      users:s.users?.users || [], categories:s.services?.categories || [], services:s.services?.services || [],
      employees:s.employees?.employees || [], schedules:s.employees?.schedules || [], clients:s.clients?.clients || [],
      appointments:s.appointments?.appointments || [], productCategories:s.inventory?.productCategories || [], products:s.inventory?.products || [], movements:s.inventory?.movements || [],
      sales:s.commerce?.sales || [], payments:s.commerce?.payments || [], expenses:s.commerce?.expenses || [],
      membershipPlans:s.memberships?.membershipPlans || [], clientMemberships:s.memberships?.clientMemberships || [], giftCards:s.memberships?.giftCards || [],
      auditLogs:s.audit?.auditLogs || []
    };
  }
  async function loadDb(){
    try {
      const saved=localStorage.getItem(DB_KEY);
      if(saved){ db=JSON.parse(saved); }
      else {
        const names=['business','users','services','employees','clients','appointments','inventory','commerce','memberships','audit'];
        try {
          const rows=await Promise.all(names.map(async name=>{
            const res=await fetch(`json/${name}.json`,{cache:'no-store'});
            if(!res.ok) throw new Error(`No se pudo cargar ${name}.json`);
            return [name,await res.json()];
          }));
          db=buildSeed(Object.fromEntries(rows));
        } catch {
          db=buildSeed();
        }
      }
    } catch { db=buildSeed(); }
    if(!db || !db.business) db=buildSeed();
    saveDb();
  }
  function saveDb(){ localStorage.setItem(DB_KEY, JSON.stringify(db)); }
  function resetDb(){ db=buildSeed(); saveDb(); toast('Datos demo restaurados.','good'); render(); }
  function session(){ try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null');}catch{return null;} }
  function currentUser(){ const s=session(); return s ? byId(db.users,s.userId) : null; }
  function loginUser(user){ localStorage.setItem(SESSION_KEY,JSON.stringify({userId:user.id,at:new Date().toISOString()})); audit('Login','ApplicationUser',user.id,`Inicio de sesión: ${user.email}`); location.hash='#dashboard'; }
  function logout(){ const u=currentUser(); if(u) audit('Logout','ApplicationUser',u.id,'Cierre de sesión'); localStorage.removeItem(SESSION_KEY); location.hash='#home'; render(); }
  function hasRole(...roles){ const u=currentUser(); return !!u && roles.some(r => (u.roles||[]).includes(r)); }
  function canManage(){ return hasRole('SuperAdmin','Admin','Manager'); }
  function canCash(){ return hasRole('SuperAdmin','Admin','Manager','Receptionist','Cashier'); }
  function canFrontDesk(){ return hasRole('SuperAdmin','Admin','Manager','Receptionist'); }
  function canInventory(){ return hasRole('SuperAdmin','Admin','Manager','Cashier'); }
  function canAudit(){ return hasRole('SuperAdmin','Admin'); }

  function audit(action, entityName, entityId, details){
    if(!db) return;
    const u=currentUser();
    db.auditLogs.push({id:nextId(db.auditLogs),spaBusinessId:1,userId:u?.id||null,action,entityName,entityId:String(entityId??''),details,ipAddress:'browser/local',createdAt:new Date().toISOString()});
    saveDb();
  }

  function toast(message,type=''){
    const el=document.createElement('div'); el.className=`toast ${type}`; el.textContent=message; TOASTS.appendChild(el); setTimeout(()=>el.remove(),3200);
  }
  function showModal(title, body, wide=false){
    MODAL.innerHTML=`<div class="modal-backdrop" data-action="close-modal"><section class="modal ${wide?'wide':''}" role="dialog" aria-modal="true"><div class="modal-head"><h2>${esc(title)}</h2><button class="modal-close" type="button" data-action="close-modal" aria-label="Cerrar">×</button></div><div class="modal-body" data-modal-body>${body}</div></section></div>`;
  }
  function closeModal(){ MODAL.innerHTML=''; }

  function statusClass(status){
    if(['Completed','Paid','Confirmed'].includes(status)) return 'good';
    if(['Pending','Partial','CheckedIn'].includes(status)) return 'warn';
    if(['Cancelled','NoShow','Refunded'].includes(status)) return 'danger';
    if(['InService'].includes(status)) return 'info'; return '';
  }
  const statusLabel = s => ({Pending:'Pendiente',Confirmed:'Confirmada',CheckedIn:'Check-in',InService:'En servicio',Completed:'Completada',Cancelled:'Cancelada',NoShow:'No asistió',Partial:'Parcial',Paid:'Pagado',Refunded:'Reembolsado'}[s]||s);
  const sourceLabel = s => ({Reception:'Recepción',Phone:'Teléfono',WhatsApp:'WhatsApp',Web:'Web',SocialMedia:'Redes sociales',WalkIn:'Sin reserva'}[s]||s);
  const methodLabel = s => ({Cash:'Efectivo',Card:'Tarjeta',Qr:'QR',Transfer:'Transferencia',GiftCard:'Gift card',Other:'Otro'}[s]||s);

  function route(){
    const raw=(location.hash||'#home').slice(1).split('?')[0];
    return raw || 'home';
  }
  function navigate(view){ location.hash=`#${view}`; }

  function render(){
    const r=route();
    const u=currentUser();
    if(!u){
      if(r==='login') return renderLogin();
      if(r==='booking') return renderBooking();
      if(r==='booking-success') return renderBookingSuccess();
      return renderPublicHome();
    }
    currentView = ['home','login','booking','booking-success'].includes(r) ? 'dashboard' : r;
    renderShell();
  }

  function renderPublicHome(){
    APP.innerHTML=`<div class="public-shell">
      <nav class="public-nav"><a class="brand-lockup" href="#home"><img src="assets/img/logo-mark.svg" alt=""><span class="brand-text"><strong>SpaFlow</strong><span>Gestión integral para SPA</span></span></a><div class="public-actions"><a class="btn" href="#booking">Reserva online</a><a class="btn primary" href="#login">Ingresar</a></div></nav>
      <section class="hero"><div class="hero-copy"><div class="eyebrow">SPA MANAGEMENT</div><h1>Bienestar organizado, operación bajo control.</h1><p>Versión web de SpaFlow convertida a HTML, CSS, JavaScript y JSON. Gestiona reservas, clientes, tratamientos, profesionales, inventario y operación comercial desde un único panel.</p><div class="hero-actions"><a class="btn primary" href="#login">${icon('shield')} Ingresar al sistema</a><a class="btn" href="#booking">${icon('calendar')} Reservar tratamiento</a></div></div>
      <aside class="hero-card"><div class="mini-grid"><div class="mini-stat"><span class="muted small">Servicios</span><b>${db.services.filter(x=>x.isActive).length}</b></div><div class="mini-stat"><span class="muted small">Profesionales</span><b>${db.employees.filter(x=>x.isActive).length}</b></div><div class="mini-stat"><span class="muted small">Cabinas</span><b>${db.rooms.filter(x=>x.isActive).length}</b></div><div class="mini-stat"><span class="muted small">Reserva web</span><b>24/7</b></div></div><div class="feature-list"><div class="feature"><span class="feature-icon">${icon('calendar')}</span><div><strong>Agenda sin cruces</strong><div class="muted small">Valida profesional y cabina antes de registrar.</div></div></div><div class="feature"><span class="feature-icon">${icon('users')}</span><div><strong>CRM de clientes</strong><div class="muted small">Consentimientos, alergias, puntos e historial.</div></div></div><div class="feature"><span class="feature-icon">${icon('chart')}</span><div><strong>Indicadores y reportes</strong><div class="muted small">Ingresos, servicios y actividad operativa.</div></div></div></div></aside></section>
    </div>`;
  }

  function renderLogin(){
    APP.innerHTML=`<div class="auth-wrap"><section class="auth-art"><div class="brand-lockup"><img src="assets/img/logo-mark.svg" alt=""><span class="brand-text"><strong>SpaFlow</strong><span style="color:#d5c8ce">Gestión integral para SPA</span></span></div><div><div class="eyebrow" style="color:#d9b7c6">ACCESO DEL EQUIPO</div><h1>Tu operación diaria, en un solo lugar.</h1><p>Accede con uno de los perfiles de demostración. En esta conversión estática la sesión se guarda en este navegador.</p></div><small style="color:#bfaeb6">HTML · CSS · JavaScript · JSON · localStorage</small></section><section class="auth-panel"><div class="auth-card"><a class="brand-lockup" href="#home"><img src="assets/img/logo-mark.svg" alt=""><span class="brand-text"><strong>SpaFlow</strong><span>Acceso</span></span></a><div style="margin-top:32px"><div class="eyebrow">BIENVENIDA</div><h2>Iniciar sesión</h2><p>Usa tu correo y contraseña.</p></div><form id="loginForm"><label class="field">Correo<input name="email" type="email" autocomplete="username" required value="admin@spaflow.local"></label><label class="field" style="margin-top:12px">Contraseña<input name="password" type="password" autocomplete="current-password" required value="ChangeMe123!"></label><button class="btn primary" style="width:100%;margin-top:18px" type="submit">Ingresar al sistema</button></form><details class="demo-credentials"><summary>Credenciales demo</summary><div class="cred-grid">${db.users.filter(x=>x.active).map(u=>`<div class="cred-row"><span>${esc((u.roles||[])[0])}</span><span><b>${esc(u.email)}</b> · ${esc(u.password)}</span></div>`).join('')}</div></details><div style="display:flex;justify-content:space-between;margin-top:18px"><a class="link-btn" href="#home">Volver</a><a class="link-btn" href="#booking">Reserva pública</a></div></div></section></div>`;
  }

  function renderBooking(){
    const services=db.services.filter(x=>x.isActive), employees=db.employees.filter(x=>x.isActive);
    APP.innerHTML=`<div class="public-shell"><nav class="public-nav"><a class="brand-lockup" href="#home"><img src="assets/img/logo-mark.svg" alt=""><span class="brand-text"><strong>SpaFlow</strong><span>Reserva online</span></span></a><div class="public-actions"><a class="btn" href="#home">Inicio</a><a class="btn primary" href="#login">Equipo</a></div></nav><div class="booking-shell"><section class="booking-card"><div class="eyebrow">RESERVA ONLINE</div><h1 style="font-size:2.3rem;letter-spacing:-.05em;margin:8px 0">Agenda tu momento de bienestar</h1><p class="muted">Completa tus datos y selecciona tratamiento, profesional y horario. La solicitud quedará pendiente de confirmación.</p><form id="publicBookingForm"><div class="form-grid"><label class="field">Nombre completo<input name="fullName" maxlength="150" required></label><label class="field">Teléfono / WhatsApp<input name="phone" maxlength="30" required></label><label class="field">Correo<input name="email" type="email" maxlength="150"></label><label class="field">Servicio<select name="serviceId" required>${services.map(s=>`<option value="${s.id}">${esc(s.name)} · ${money(s.price)}</option>`).join('')}</select></label><label class="field">Profesional<select name="employeeId" required>${employees.map(e=>`<option value="${e.id}">${esc(e.fullName)}</option>`).join('')}</select></label><label class="field">Fecha y hora<input name="startAt" type="datetime-local" required value="${esc(defaultFutureDateTime(24))}"></label><label class="field span-2">Comentario opcional<textarea name="notes" maxlength="500"></textarea></label></div><label class="check" style="margin-top:14px"><input type="checkbox" name="contactConsent" required> Autorizo que me contacten para confirmar esta reserva.</label><div class="form-actions"><button class="btn" type="button" data-nav="home">Cancelar</button><button class="btn primary" type="submit">Solicitar reserva</button></div></form></section></div></div>`;
  }
  function renderBookingSuccess(){
    const id=sessionStorage.getItem('spaflow_last_booking'); const a=byId(db.appointments,id); const c=a?byId(db.clients,a.clientId):null;
    APP.innerHTML=`<div class="public-shell"><nav class="public-nav"><a class="brand-lockup" href="#home"><img src="assets/img/logo-mark.svg" alt=""><span class="brand-text"><strong>SpaFlow</strong><span>Reserva online</span></span></a></nav><div class="booking-shell"><section class="booking-card success-card"><div class="success-mark">${icon('check','lg')}</div><div class="eyebrow">SOLICITUD REGISTRADA</div><h1>Gracias${c?`, ${esc(c.fullName.split(' ')[0])}`:''}.</h1><p class="muted">Tu reserva quedó pendiente de confirmación.${a?` Horario solicitado: <strong>${fmtDateTime(a.startAt)}</strong>.`:''}</p><div class="hero-actions" style="justify-content:center"><a class="btn primary" href="#home">Volver al inicio</a><a class="btn" href="#booking">Nueva reserva</a></div></section></div></div>`;
  }

  function defaultFutureDateTime(hours=1){ const d=new Date(Date.now()+hours*3600000); d.setMinutes(Math.ceil(d.getMinutes()/15)*15,0,0); return dateTimeLocal(d); }

  const NAV = [
    ['dashboard','home','Resumen'],['appointments','calendar','Agenda'],['clients','users','Clientes'],['services','heart','Servicios'],['employees','users','Equipo'],['inventory','package','Inventario'],
    ['sales','receipt','Ventas y pagos'],['expenses','money','Gastos'],['memberships','gift','Membresías y gift cards'],['reports','chart','Reportes'],['settings','settings','Configuración'],['audit','shield','Auditoría']
  ];
  function allowedView(v){
    if(v==='settings') return canManage();
    if(v==='audit') return canAudit();
    if(v==='sales') return canCash() || hasRole('Therapist');
    if(v==='expenses') return canCash();
    if(v==='memberships') return canFrontDesk() || hasRole('Cashier');
    return true;
  }

  function renderShell(){
    const u=currentUser(); if(!u){navigate('home');return;}
    if(!allowedView(currentView)) currentView='dashboard';
    const viewTitle=({dashboard:'Resumen',appointments:'Agenda',clients:'Clientes',services:'Servicios',employees:'Equipo',inventory:'Inventario',sales:'Ventas y pagos',expenses:'Gastos',memberships:'Membresías',reports:'Reportes',settings:'Configuración',audit:'Auditoría'})[currentView]||'SpaFlow';
    APP.innerHTML=`<div class="app-shell"><aside class="sidebar ${sidebarOpen?'open':''}" id="sidebar"><a class="side-brand" href="#dashboard"><img src="assets/img/logo-mark.svg" alt=""><span><strong>SpaFlow</strong><small>Gestión integral para SPA</small></span></a><div class="nav-group-label">Operación</div><nav class="side-nav">${NAV.filter(([v])=>allowedView(v)).map(([v,i,l])=>`<button class="${currentView===v?'active':''}" type="button" data-nav="${v}">${icon(i)}<span>${esc(l)}</span>${v==='inventory'&&lowStock().length?`<span class="nav-badge">${lowStock().length}</span>`:''}</button>`).join('')}</nav><div class="sidebar-footer"><div class="user-chip"><strong>${esc(u.fullName)}</strong><span>${esc((u.roles||[]).join(' · '))}</span></div><button class="btn" style="width:100%;background:transparent;color:#fff;border-color:#55464e" type="button" data-action="logout">${icon('logout')} Cerrar sesión</button></div></aside><section class="main-area"><header class="topbar"><div class="top-left"><button class="btn icon-only mobile-menu" type="button" data-action="toggle-sidebar" aria-label="Menú">${icon('menu')}</button><div><h2>${esc(viewTitle)}</h2><small>${esc(db.business.name)}</small></div></div><div class="top-actions"><span class="date-chip small muted">${new Intl.DateTimeFormat('es-BO',{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(new Date())}</span><button class="btn sm" type="button" data-action="quick-book">${icon('plus','sm')} Reserva</button></div></header><main class="content" id="viewRoot">${renderView(currentView)}</main></section></div>`;
  }
  function renderView(v){ return ({dashboard:renderDashboard,appointments:renderAppointments,clients:renderClients,services:renderServices,employees:renderEmployees,inventory:renderInventory,sales:renderSales,expenses:renderExpenses,memberships:renderMemberships,reports:renderReports,settings:renderSettings,audit:renderAudit}[v]||renderDashboard)(); }

  function lowStock(){ return db.products.filter(p=>p.isActive && Number(p.stock)<=Number(p.minimumStock)); }
  function todayAppointments(){ const t=new Date(); return db.appointments.filter(a=>a.isActive!==false && isSameDay(a.startAt,t) && a.status!=='Cancelled'); }
  function revenueBetween(from,to){ return db.payments.filter(p=>p.status==='Paid'&&new Date(p.paidAt)>=from&&new Date(p.paidAt)<=to).reduce((s,p)=>s+Number(p.amount||0),0); }
  function renderDashboard(){
    const aps=todayAppointments(); const confirmed=aps.filter(a=>a.status==='Confirmed').length; const activeClients=db.clients.filter(c=>c.isActive).length; const rev=revenueBetween(startOfDay(new Date()),endOfDay(new Date())); const upcoming=db.appointments.filter(a=>new Date(a.startAt)>=new Date()&&!['Cancelled','NoShow'].includes(a.status)).sort((a,b)=>new Date(a.startAt)-new Date(b.startAt)).slice(0,8); const lows=lowStock().slice(0,8);
    return `<div class="page-heading"><div><div class="eyebrow">OPERACIÓN</div><h1>Resumen del día</h1><p>Indicadores de ${esc(db.business.name)}.</p></div><div class="heading-actions"><button class="btn primary" data-action="quick-book">${icon('plus')} Nueva reserva</button></div></div><section class="metric-grid">${metric('Citas de hoy',aps.length,'calendar')}${metric('Confirmadas',confirmed,'check')}${metric('Clientes activos',activeClients,'users')}${metric('Ingresos hoy',money(rev),'money')}</section><div class="grid-2"><section class="card"><div class="card-head"><div><h3>Próximas citas</h3><div class="sub">Siguiente actividad programada</div></div><button class="link-btn" data-nav="appointments">Ver agenda</button></div>${upcoming.length?`<div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Cliente</th><th>Profesional</th><th>Estado</th></tr></thead><tbody>${upcoming.map(a=>`<tr><td><strong>${fmtDateTime(a.startAt)}</strong></td><td>${esc(byId(db.clients,a.clientId)?.fullName||'—')}</td><td>${esc(byId(db.employees,a.employeeId)?.fullName||'—')}</td><td><span class="status ${statusClass(a.status)}">${statusLabel(a.status)}</span></td></tr>`).join('')}</tbody></table></div>`:empty('calendar','No hay reservas próximas.')}</section><section class="card"><div class="card-head"><div><h3>Alertas de inventario</h3><div class="sub">Productos en o bajo mínimo</div></div><button class="link-btn" data-nav="inventory">Inventario</button></div>${lows.length?`<ul class="clean-list">${lows.map(p=>`<li><span><strong>${esc(p.name)}</strong><br><small class="muted">${esc(p.sku||'Sin SKU')}</small></span><span><b>${p.stock}</b> / mín. ${p.minimumStock}</span></li>`).join('')}</ul>`:empty('package','Sin productos con stock crítico.')}</section></div>`;
  }
  function metric(label,value,ico){return `<article class="metric-card"><div class="metric-top"><span>${esc(label)}</span><span class="metric-icon">${icon(ico)}</span></div><strong>${typeof value==='string'?value:esc(value)}</strong></article>`;}
  function empty(ico,text){return `<div class="empty-state"><div class="empty-icon">${icon(ico,'lg')}</div><div>${esc(text)}</div></div>`;}

  function appointmentRows(list){
    return list.map(a=>{ const c=byId(db.clients,a.clientId),e=byId(db.employees,a.employeeId),r=byId(db.rooms,a.roomId); const names=(a.items||[]).map(i=>byId(db.services,i.spaServiceId)?.name).filter(Boolean).join(', '); return `<tr><td><strong>${fmtTime(a.startAt)}</strong><br><small>${fmtTime(a.endAt)}</small></td><td><strong>${esc(c?.fullName||'—')}</strong><br><small>${esc(c?.phone||'')}</small></td><td>${esc(names||'—')}</td><td>${esc(e?.fullName||'—')}</td><td>${esc(r?.name||'—')}</td><td><span class="status ${statusClass(a.status)}">${statusLabel(a.status)}</span><br><small>${statusLabel(a.paymentStatus)}</small></td><td>${money(a.total)}</td><td><div class="table-actions"><button class="btn sm" data-action="appointment-detail" data-id="${a.id}">Ver</button>${canFrontDesk()||hasRole('Therapist')?`<button class="btn sm soft" data-action="appointment-next" data-id="${a.id}">Avanzar</button>`:''}${canCash()&&a.paymentStatus!=='Paid'&&!['Cancelled','NoShow'].includes(a.status)?`<button class="btn sm good" data-action="appointment-pay" data-id="${a.id}">Cobrar</button>`:''}</div></td></tr>`; }).join('');
  }
  function renderAppointments(){
    const params=new URLSearchParams((location.hash.split('?')[1]||'')); const date=params.get('date')||todayISO(); const status=params.get('status')||''; let list=db.appointments.filter(a=>(a.startAt||'').slice(0,10)===date && a.isActive!==false).sort((a,b)=>new Date(a.startAt)-new Date(b.startAt)); if(status) list=list.filter(a=>a.status===status);
    return `<div class="page-heading"><div><div class="eyebrow">RESERVAS</div><h1>Agenda</h1><p>Reservas, estados, cabinas y cobros.</p></div><div class="heading-actions">${canFrontDesk()?`<button class="btn primary" data-action="quick-book">${icon('plus')} Nueva reserva</button>`:''}</div></div><div class="filter-bar"><label class="field"><span>Fecha</span><input id="appointmentDateFilter" type="date" value="${esc(date)}"></label><label class="field"><span>Estado</span><select id="appointmentStatusFilter"><option value="">Todos</option>${['Pending','Confirmed','CheckedIn','InService','Completed','Cancelled','NoShow'].map(s=>`<option value="${s}" ${status===s?'selected':''}>${statusLabel(s)}</option>`).join('')}</select></label><button class="btn" data-action="apply-appointment-filter">Filtrar</button></div><section class="card">${list.length?`<div class="table-wrap"><table><thead><tr><th>Hora</th><th>Cliente</th><th>Servicio</th><th>Profesional</th><th>Cabina</th><th>Estado</th><th>Total</th><th>Acciones</th></tr></thead><tbody>${appointmentRows(list)}</tbody></table></div>`:empty('calendar','No hay reservas para esta fecha.')}</section>`;
  }

  function renderClients(){
    const params=new URLSearchParams((location.hash.split('?')[1]||'')); const search=(params.get('q')||'').trim().toLowerCase(); let list=db.clients.filter(c=>c.isActive); if(search) list=list.filter(c=>[c.fullName,c.phone,c.email].some(x=>String(x||'').toLowerCase().includes(search)));
    return `<div class="page-heading"><div><div class="eyebrow">CRM</div><h1>Clientes</h1><p>Datos de contacto, consentimientos e historial.</p></div><div class="heading-actions">${canFrontDesk()||canManage()?`<button class="btn primary" data-action="new-client">${icon('plus')} Nuevo cliente</button>`:''}</div></div><div class="filter-bar"><label class="field search"><span>Buscar</span><input id="clientSearch" value="${esc(params.get('q')||'')}" placeholder="Nombre, teléfono o correo"></label><button class="btn" data-action="search-client">${icon('search','sm')} Buscar</button></div><section class="card">${list.length?`<div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Teléfono</th><th>Correo</th><th>Puntos</th><th>Última visita</th><th></th></tr></thead><tbody>${list.sort((a,b)=>a.fullName.localeCompare(b.fullName)).map(c=>`<tr><td><strong>${esc(c.fullName)}</strong></td><td>${esc(c.phone||'—')}</td><td>${esc(c.email||'—')}</td><td>${Number(c.loyaltyPoints||0)}</td><td>${fmtDate(c.lastVisitAt)}</td><td><div class="table-actions"><button class="btn sm" data-action="client-detail" data-id="${c.id}">Ver</button>${canFrontDesk()||canManage()?`<button class="btn sm soft" data-action="edit-client" data-id="${c.id}">${icon('edit','sm')} Editar</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`:empty('users','No se encontraron clientes.')}</section>`;
  }

  function renderServices(){
    const list=db.services.filter(s=>s.isActive).sort((a,b)=>{const ca=byId(db.categories,a.serviceCategoryId)?.displayOrder||0,cb=byId(db.categories,b.serviceCategoryId)?.displayOrder||0;return ca-cb||a.name.localeCompare(b.name)});
    return `<div class="page-heading"><div><div class="eyebrow">CATÁLOGO</div><h1>Servicios</h1><p>Tratamientos, duración, precio y comisión.</p></div><div class="heading-actions">${canManage()?`<button class="btn primary" data-action="new-service">${icon('plus')} Nuevo servicio</button>`:''}</div></div><section class="card">${list.length?`<div class="table-wrap"><table><thead><tr><th>Servicio</th><th>Categoría</th><th>Duración</th><th>Precio</th><th>Comisión</th><th>Cabina</th><th></th></tr></thead><tbody>${list.map(s=>`<tr><td><strong>${esc(s.name)}</strong><br><small>${esc(s.description||'')}</small></td><td>${esc(byId(db.categories,s.serviceCategoryId)?.name||'—')}</td><td>${s.durationMinutes} min</td><td>${money(s.price)}</td><td>${Number(s.defaultCommissionPercent||0)}%</td><td>${s.requiresRoom?'Sí':'No'}</td><td>${canManage()?`<button class="btn sm soft" data-action="edit-service" data-id="${s.id}">${icon('edit','sm')} Editar</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:empty('heart','No hay servicios activos.')}</section>`;
  }

  function renderEmployees(){
    const list=db.employees.filter(e=>e.isActive);
    return `<div class="page-heading"><div><div class="eyebrow">PERSONAL</div><h1>Equipo</h1><p>Profesionales, especialidades y servicios habilitados.</p></div><div class="heading-actions">${canManage()?`<button class="btn primary" data-action="new-employee">${icon('plus')} Nuevo profesional</button>`:''}</div></div><div class="profile-grid">${list.map(e=>`<article class="profile-card"><div class="avatar">${esc(e.fullName.slice(0,1).toUpperCase())}</div><div style="min-width:0;flex:1"><h3>${esc(e.fullName)}</h3><p>${esc(e.specialty||'Profesional')}</p><small>${esc(byId(db.branches,e.branchId)?.name||'—')} · Comisión ${Number(e.commissionPercent||0)}%</small><div class="chips" style="margin-top:9px">${(e.serviceIds||[]).map(id=>byId(db.services,id)).filter(Boolean).slice(0,3).map(s=>`<span class="chip">${esc(s.name)}</span>`).join('')}</div>${canManage()?`<div style="margin-top:12px"><button class="btn sm soft" data-action="edit-employee" data-id="${e.id}">${icon('edit','sm')} Editar</button></div>`:''}</div></article>`).join('')}${list.length?'':empty('users','Aún no se registraron profesionales.')}</div>`;
  }

  function renderInventory(){
    const list=db.products.filter(p=>p.isActive).sort((a,b)=>a.name.localeCompare(b.name));
    return `<div class="page-heading"><div><div class="eyebrow">STOCK</div><h1>Inventario</h1><p>Productos, mínimos y movimientos de existencias.</p></div><div class="heading-actions">${canInventory()?`<button class="btn primary" data-action="new-product">${icon('plus')} Nuevo producto</button>`:''}<button class="btn" data-action="inventory-movements">Movimientos</button></div></div>${lowStock().length?`<div class="report-note" style="margin-bottom:14px">Hay <strong>${lowStock().length}</strong> producto(s) con stock igual o menor al mínimo configurado.</div>`:''}<section class="card"><div class="table-wrap"><table><thead><tr><th>Producto</th><th>SKU</th><th>Categoría</th><th>Stock</th><th>Mínimo</th><th>Costo</th><th>Precio venta</th><th></th></tr></thead><tbody>${list.map(p=>`<tr class="${Number(p.stock)<=Number(p.minimumStock)?'warning-row':''}"><td><strong>${esc(p.name)}</strong></td><td>${esc(p.sku||'—')}</td><td>${esc(byId(db.productCategories,p.productCategoryId)?.name||'—')}</td><td><strong>${Number(p.stock)}</strong></td><td>${Number(p.minimumStock)}</td><td>${money(p.cost)}</td><td>${money(p.salePrice)}</td><td>${canInventory()?`<div class="table-actions"><button class="btn sm" data-action="stock-adjust" data-id="${p.id}">Ajustar</button><button class="btn sm soft" data-action="edit-product" data-id="${p.id}">${icon('edit','sm')}</button></div>`:''}</td></tr>`).join('')}</tbody></table></div></section>`;
  }

  function renderSales(){
    const sales=[...db.sales].sort((a,b)=>new Date(b.soldAt)-new Date(a.soldAt)); const paid=db.payments.filter(p=>p.status==='Paid').sort((a,b)=>new Date(b.paidAt)-new Date(a.paidAt)).slice(0,10);
    return `<div class="page-heading"><div><div class="eyebrow">COMERCIO</div><h1>Ventas y pagos</h1><p>Ventas de productos/servicios y cobros vinculados.</p></div><div class="heading-actions">${canCash()?`<button class="btn primary" data-action="new-sale">${icon('plus')} Nueva venta</button>`:''}</div></div><section class="metric-grid">${metric('Ventas registradas',sales.length,'receipt')}${metric('Pagos totales',db.payments.filter(p=>p.status==='Paid').length,'card')}${metric('Ingresos 30 días',money(revenueBetween(startOfDay(new Date(Date.now()-29*86400000)),endOfDay(new Date()))),'money')}${metric('Ticket venta',money(sales.length?sales.reduce((s,x)=>s+Number(x.total),0)/sales.length:0),'tag')}</section><div class="grid-2"><section class="card"><div class="card-head"><h3>Ventas</h3></div>${sales.length?`<div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Cliente</th><th>Ítems</th><th>Total</th><th></th></tr></thead><tbody>${sales.map(s=>`<tr><td>${fmtDateTime(s.soldAt)}</td><td>${esc(byId(db.clients,s.clientId)?.fullName||'Cliente general')}</td><td>${(s.items||[]).reduce((n,i)=>n+Number(i.quantity||0),0)}</td><td><strong>${money(s.total)}</strong></td><td><button class="btn sm" data-action="sale-detail" data-id="${s.id}">Ver</button></td></tr>`).join('')}</tbody></table></div>`:empty('receipt','No hay ventas registradas.')}</section><section class="card"><div class="card-head"><h3>Últimos pagos</h3></div><ul class="clean-list">${paid.map(p=>`<li><span><strong>${money(p.amount)}</strong><br><small class="muted">${methodLabel(p.method)} · ${fmtDateTime(p.paidAt)}</small></span><span class="status good">Pagado</span></li>`).join('')||'<li class="muted">Sin pagos</li>'}</ul></section></div>`;
  }

  function renderExpenses(){
    const list=[...db.expenses].sort((a,b)=>new Date(b.expenseAt)-new Date(a.expenseAt)); const monthStart=new Date(); monthStart.setDate(1); monthStart.setHours(0,0,0,0); const total=list.filter(x=>new Date(x.expenseAt)>=monthStart).reduce((s,x)=>s+Number(x.amount),0);
    return `<div class="page-heading"><div><div class="eyebrow">EGRESOS</div><h1>Gastos</h1><p>Registro operativo de egresos del SPA.</p></div><div class="heading-actions"><button class="btn primary" data-action="new-expense">${icon('plus')} Registrar gasto</button></div></div><section class="metric-grid">${metric('Gastos del mes',money(total),'money')}${metric('Registros',list.length,'receipt')}</section><section class="card">${list.length?`<div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Concepto</th><th>Monto</th><th>Notas</th><th></th></tr></thead><tbody>${list.map(x=>`<tr><td>${fmtDateTime(x.expenseAt)}</td><td><strong>${esc(x.concept)}</strong></td><td>${money(x.amount)}</td><td>${esc(x.notes||'—')}</td><td>${canManage()?`<button class="btn sm danger" data-action="delete-expense" data-id="${x.id}">${icon('trash','sm')}</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:empty('money','No hay gastos registrados.')}</section>`;
  }

  function renderMemberships(){
    const activeMemberships=db.clientMemberships.filter(m=>m.isActive!==false && new Date(m.endDate)>=startOfDay(new Date()));
    return `<div class="page-heading"><div><div class="eyebrow">FIDELIZACIÓN</div><h1>Membresías y gift cards</h1><p>Planes, asignaciones y saldos promocionales.</p></div><div class="heading-actions">${canFrontDesk()||canManage()?`<button class="btn primary" data-action="new-membership">${icon('plus')} Asignar membresía</button><button class="btn" data-action="new-giftcard">${icon('gift','sm')} Gift card</button>`:''}</div></div><div class="grid-2"><section class="card"><div class="card-head"><h3>Membresías activas</h3></div>${activeMemberships.length?`<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Plan</th><th>Inicio</th><th>Vence</th></tr></thead><tbody>${activeMemberships.map(m=>`<tr><td>${esc(byId(db.clients,m.clientId)?.fullName||'—')}</td><td>${esc(byId(db.membershipPlans,m.membershipPlanId)?.name||'—')}</td><td>${fmtDate(m.startDate)}</td><td>${fmtDate(m.endDate)}</td></tr>`).join('')}</tbody></table></div>`:empty('gift','No hay membresías activas.')}</section><section class="card"><div class="card-head"><h3>Gift cards</h3></div><ul class="clean-list">${db.giftCards.filter(g=>g.isActive!==false).map(g=>`<li><span><strong>${esc(g.code)}</strong><br><small class="muted">${esc(byId(db.clients,g.assignedClientId)?.fullName||'Sin asignar')}</small></span><span><b>${money(g.currentBalance)}</b><br><small class="muted">Vence ${fmtDate(g.expiresOn)}</small></span></li>`).join('')||'<li class="muted">Sin gift cards</li>'}</ul></section></div><section class="card" style="margin-top:16px"><div class="card-head"><h3>Planes disponibles</h3>${canManage()?`<button class="btn sm soft" data-action="new-plan">${icon('plus','sm')} Nuevo plan</button>`:''}</div><div class="profile-grid">${db.membershipPlans.filter(p=>p.isActive!==false).map(p=>`<article class="profile-card"><div class="avatar">${icon('gift')}</div><div><h3>${esc(p.name)}</h3><p>${esc(p.description||'')}</p><small>${p.durationDays} días · ${p.serviceDiscountPercent}% descuento · ${money(p.price)}</small></div></article>`).join('')}</div></section>`;
  }

  function reportData(){
    const params=new URLSearchParams((location.hash.split('?')[1]||'')); const from=params.get('from')||dateAddISO(-30), to=params.get('to')||todayISO(); const start=startOfDay(new Date(from+'T00:00')), end=endOfDay(new Date(to+'T00:00'));
    const rev=revenueBetween(start,end); const completed=db.appointments.filter(a=>a.status==='Completed'&&new Date(a.startAt)>=start&&new Date(a.startAt)<=end); const newClients=db.clients.filter(c=>new Date(c.createdAt||c.createdAtUtc||0)>=start&&new Date(c.createdAt||c.createdAtUtc||0)<=end).length; const aggregate={}; db.appointments.filter(a=>a.status!=='Cancelled'&&new Date(a.startAt)>=start&&new Date(a.startAt)<=end).forEach(a=>(a.items||[]).forEach(i=>{const s=byId(db.services,i.spaServiceId);if(!s)return;aggregate[s.name]??={name:s.name,qty:0,revenue:0};aggregate[s.name].qty+=Number(i.quantity||1);aggregate[s.name].revenue+=Number(i.unitPrice||0)*Number(i.quantity||1);})); const top=Object.values(aggregate).sort((a,b)=>b.qty-a.qty); return {from,to,start,end,rev,completed,newClients,avg:completed.length?rev/completed.length:0,top};
  }
  function dateAddISO(days){const d=new Date();d.setDate(d.getDate()+days);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;}
  function renderReports(){
    const r=reportData(); const max=Math.max(...r.top.map(x=>x.qty),1);
    return `<div class="page-heading"><div><div class="eyebrow">ANÁLISIS</div><h1>Reportes</h1><p>Indicadores calculados a partir de pagos y reservas.</p></div></div><div class="filter-bar"><label class="field"><span>Desde</span><input id="reportFrom" type="date" value="${esc(r.from)}"></label><label class="field"><span>Hasta</span><input id="reportTo" type="date" value="${esc(r.to)}"></label><button class="btn" data-action="apply-report-filter">Actualizar</button></div><section class="metric-grid">${metric('Ingresos',money(r.rev),'money')}${metric('Reservas completadas',r.completed.length,'check')}${metric('Ticket promedio',money(r.avg),'card')}${metric('Nuevos clientes',r.newClients,'users')}</section><div class="grid-2"><section class="card"><div class="card-head"><h3>Servicios más reservados</h3></div>${r.top.length?`<div class="bar-list">${r.top.slice(0,10).map(x=>`<div class="bar-row"><span>${esc(x.name)}</span><div class="bar-track"><span style="width:${Math.max(6,x.qty/max*100)}%"></span></div><div class="bar-value">${x.qty}</div></div>`).join('')}</div>`:empty('chart','No hay datos en el período.')}</section><section class="card"><div class="card-head"><h3>Ingreso estimado por servicio</h3></div><ul class="clean-list">${r.top.slice(0,8).map(x=>`<li><span>${esc(x.name)}</span><strong>${money(x.revenue)}</strong></li>`).join('')||'<li class="muted">Sin datos</li>'}</ul></section></div>`;
  }

  function renderSettings(){
    const b=db.business;
    return `<div class="page-heading"><div><div class="eyebrow">ADMINISTRACIÓN</div><h1>Configuración del SPA</h1><p>Datos del negocio, sucursal y cabinas.</p></div><div class="heading-actions"><button class="btn" data-action="export-data">${icon('download','sm')} Exportar JSON</button><label class="btn" style="cursor:pointer">${icon('upload','sm')} Importar JSON<input id="importFile" type="file" accept="application/json" hidden></label></div></div><section class="card"><div class="card-head"><h3>Datos del negocio</h3></div><form id="settingsForm"><input type="hidden" name="id" value="${b.id}"><div class="form-grid cols-3"><label class="field">Nombre<input name="name" required value="${esc(b.name)}"></label><label class="field">Razón social<input name="legalName" value="${esc(b.legalName||'')}"></label><label class="field">Teléfono<input name="phone" value="${esc(b.phone||'')}"></label><label class="field">Correo<input name="email" type="email" value="${esc(b.email||'')}"></label><label class="field">Moneda<input name="currency" maxlength="10" value="${esc(b.currency||'BOB')}"></label><label class="field">Zona horaria<input name="timeZoneId" value="${esc(b.timeZoneId||'America/La_Paz')}"></label><label class="field span-2">Dirección<textarea name="address">${esc(b.address||'')}</textarea></label></div><div class="form-actions"><button class="btn primary" type="submit">Guardar cambios</button></div></form></section><div class="grid-2" style="margin-top:16px"><section class="card"><div class="card-head"><h3>Sucursales</h3><button class="btn sm soft" data-action="new-branch">${icon('plus','sm')} Agregar</button></div><ul class="clean-list">${db.branches.filter(x=>x.isActive!==false).map(x=>`<li><span><strong>${esc(x.name)}</strong><br><small class="muted">${esc(x.address||'')}</small></span><button class="btn sm soft" data-action="edit-branch" data-id="${x.id}">${icon('edit','sm')}</button></li>`).join('')}</ul></section><section class="card"><div class="card-head"><h3>Cabinas</h3><button class="btn sm soft" data-action="new-room">${icon('plus','sm')} Agregar</button></div><ul class="clean-list">${db.rooms.filter(x=>x.isActive!==false).map(x=>`<li><span><strong>${esc(x.name)}</strong><br><small class="muted">Capacidad ${x.capacity||1} · ${esc(byId(db.branches,x.branchId)?.name||'')}</small></span><button class="btn sm soft" data-action="edit-room" data-id="${x.id}">${icon('edit','sm')}</button></li>`).join('')}</ul></section></div><section class="card" style="margin-top:16px"><div class="card-head"><div><h3>Datos locales</h3><div class="sub">Esta versión reemplaza SQL Server por localStorage.</div></div><button class="btn danger" data-action="reset-data">Restablecer demo</button></div><div class="report-note">La conversión conserva la lógica funcional en el navegador. No almacenes datos reales sensibles en esta versión estática.</div></section>`;
  }

  function renderAudit(){
    const logs=[...db.auditLogs].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)).slice(0,300);
    return `<div class="page-heading"><div><div class="eyebrow">SEGURIDAD</div><h1>Auditoría</h1><p>Registro local de acciones realizadas en esta instalación.</p></div></div><section class="card">${logs.length?`<div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Entidad</th><th>Detalle</th></tr></thead><tbody>${logs.map(l=>`<tr><td>${fmtDateTime(l.createdAt)}</td><td>${esc(byId(db.users,l.userId)?.fullName||'Público')}</td><td><span class="status">${esc(l.action)}</span></td><td>${esc(l.entityName)} ${esc(l.entityId||'')}</td><td>${esc(l.details||'')}</td></tr>`).join('')}</tbody></table></div>`:empty('shield','Sin registros de auditoría.')}</section>`;
  }

  function appointmentConflict(candidate, ignoreId=null){
    const start=new Date(candidate.startAt), end=new Date(candidate.endAt); if(end<=start) return 'La hora de fin debe ser posterior a la hora de inicio.';
    const clashes=db.appointments.filter(a=>String(a.id)!==String(ignoreId)&&a.branchId===candidate.branchId&&!['Cancelled','NoShow'].includes(a.status)&&new Date(a.startAt)<end&&new Date(a.endAt)>start);
    if(clashes.some(a=>String(a.employeeId)===String(candidate.employeeId))) return 'El profesional ya tiene una reserva que se cruza con ese horario.';
    if(candidate.roomId && clashes.some(a=>String(a.roomId)===String(candidate.roomId))) return 'La cabina seleccionada ya está ocupada en ese horario.';
    return null;
  }
  function createAppointmentFromForm(fd, publicMode=false){
    const service=byId(db.services,fd.serviceId), employee=byId(db.employees,fd.employeeId), client=byId(db.clients,fd.clientId);
    if(!service||service.isActive===false||!employee||employee.isActive===false) throw new Error('Servicio o profesional inválido.');
    if(!client||client.isActive===false) throw new Error('Cliente inválido.');
    const start=new Date(fd.startAt); if(Number.isNaN(start.getTime())) throw new Error('Selecciona una fecha y hora válida.'); if(publicMode&&start<new Date(Date.now()+30*60000)) throw new Error('Selecciona un horario futuro (mínimo 30 minutos).');
    const end=new Date(start.getTime()+Number(service.durationMinutes)*60000);
    const a={id:nextId(db.appointments),spaBusinessId:1,branchId:Number(employee.branchId||1),clientId:Number(fd.clientId),employeeId:Number(fd.employeeId),roomId:fd.roomId?Number(fd.roomId):null,startAt:dateTimeLocal(start),endAt:dateTimeLocal(end),status:'Pending',source:fd.source||'Reception',paymentStatus:'Pending',total:Number(service.price),discount:0,notes:fd.notes||'',createdByUserId:currentUser()?.id||null,items:[{id:Date.now(),spaServiceId:Number(service.id),quantity:1,durationMinutes:Number(service.durationMinutes),unitPrice:Number(service.price)}],createdAt:new Date().toISOString(),isActive:true};
    const conflict=appointmentConflict(a); if(conflict) throw new Error(conflict); db.appointments.push(a); saveDb(); audit('Create','Appointment',a.id,`Reserva creada para ${fmtDateTime(a.startAt)}`); return a;
  }

  function modalAppointment(){
    showModal('Nueva reserva',`<form id="appointmentForm"><div id="modalValidation"></div><div class="form-grid"><label class="field">Cliente<select name="clientId" required>${db.clients.filter(c=>c.isActive).map(c=>`<option value="${c.id}">${esc(c.fullName)}</option>`).join('')}</select></label><label class="field">Servicio<select name="serviceId" required>${db.services.filter(s=>s.isActive).map(s=>`<option value="${s.id}">${esc(s.name)} · ${money(s.price)}</option>`).join('')}</select></label><label class="field">Profesional<select name="employeeId" required>${db.employees.filter(e=>e.isActive).map(e=>`<option value="${e.id}">${esc(e.fullName)}</option>`).join('')}</select></label><label class="field">Cabina<select name="roomId"><option value="">Sin cabina</option>${db.rooms.filter(r=>r.isActive).map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></label><label class="field">Fecha y hora<input name="startAt" type="datetime-local" required value="${esc(defaultFutureDateTime(1))}"></label><label class="field">Origen<select name="source">${['Reception','Phone','WhatsApp','Web','SocialMedia','WalkIn'].map(s=>`<option value="${s}">${sourceLabel(s)}</option>`).join('')}</select></label><label class="field span-2">Notas<textarea name="notes" maxlength="700"></textarea></label></div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Guardar reserva</button></div></form>`);
  }
  function modalClient(client=null){
    const c=client||{}; showModal(client?'Editar cliente':'Nuevo cliente',`<form id="clientForm"><input type="hidden" name="id" value="${esc(c.id||'')}"><div class="form-grid"><label class="field">Nombre completo<input name="fullName" maxlength="150" required value="${esc(c.fullName||'')}"></label><label class="field">Teléfono<input name="phone" maxlength="30" value="${esc(c.phone||'')}"></label><label class="field">Correo<input name="email" type="email" maxlength="150" value="${esc(c.email||'')}"></label><label class="field">Fecha de nacimiento<input name="birthDate" type="date" value="${esc(c.birthDate||'')}"></label><label class="field span-2">Alergias / sensibilidades<textarea name="allergies" maxlength="500">${esc(c.allergies||'')}</textarea></label><label class="field span-2">Contraindicaciones informadas<textarea name="contraindications" maxlength="500">${esc(c.contraindications||'')}</textarea></label><label class="field span-2">Notas<textarea name="notes" maxlength="500">${esc(c.notes||'')}</textarea></label></div><div class="form-grid"><label class="check"><input type="checkbox" name="treatmentConsent" ${c.treatmentConsent?'checked':''}> Consentimiento para registrar información del tratamiento</label><label class="check"><input type="checkbox" name="marketingConsent" ${c.marketingConsent?'checked':''}> Acepta comunicaciones comerciales</label></div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Guardar cliente</button></div></form>`);
  }
  function modalClientDetail(id){
    const c=byId(db.clients,id); if(!c)return; const aps=db.appointments.filter(a=>String(a.clientId)===String(id)).sort((a,b)=>new Date(b.startAt)-new Date(a.startAt));
    showModal(c.fullName,`<div class="grid-2"><div><div class="kv"><span>Teléfono</span><strong>${esc(c.phone||'—')}</strong></div><div class="kv"><span>Correo</span><strong>${esc(c.email||'—')}</strong></div><div class="kv"><span>Nacimiento</span><strong>${fmtDate(c.birthDate)}</strong></div><div class="kv"><span>Puntos</span><strong>${Number(c.loyaltyPoints||0)}</strong></div><div class="kv"><span>Alergias</span><strong>${esc(c.allergies||'—')}</strong></div><div class="kv"><span>Contraindicaciones</span><strong>${esc(c.contraindications||'—')}</strong></div></div><div><div class="kv"><span>Consentimiento tratamiento</span><strong>${c.treatmentConsent?'Sí':'No'}</strong></div><div class="kv"><span>Marketing</span><strong>${c.marketingConsent?'Sí':'No'}</strong></div><div class="kv"><span>Última visita</span><strong>${fmtDate(c.lastVisitAt)}</strong></div><div class="kv"><span>Notas</span><strong>${esc(c.notes||'—')}</strong></div></div></div><h3 style="margin-top:20px">Historial de reservas</h3>${aps.length?`<div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Servicio</th><th>Estado</th><th>Total</th></tr></thead><tbody>${aps.map(a=>`<tr><td>${fmtDateTime(a.startAt)}</td><td>${esc((a.items||[]).map(i=>byId(db.services,i.spaServiceId)?.name).filter(Boolean).join(', '))}</td><td><span class="status ${statusClass(a.status)}">${statusLabel(a.status)}</span></td><td>${money(a.total)}</td></tr>`).join('')}</tbody></table></div>`:empty('calendar','Sin historial de reservas.')}`,true);
  }
  function modalService(service=null){
    const s=service||{}; showModal(service?'Editar servicio':'Nuevo servicio',`<form id="serviceForm"><input type="hidden" name="id" value="${esc(s.id||'')}"><div class="form-grid"><label class="field">Nombre<input name="name" required maxlength="140" value="${esc(s.name||'')}"></label><label class="field">Categoría<select name="serviceCategoryId">${db.categories.filter(c=>c.isActive).map(c=>`<option value="${c.id}" ${String(c.id)===String(s.serviceCategoryId)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label class="field">Duración (min)<input name="durationMinutes" type="number" min="5" step="5" required value="${esc(s.durationMinutes||60)}"></label><label class="field">Precio<input name="price" type="number" min="0" step="0.01" required value="${esc(s.price||0)}"></label><label class="field">Comisión %<input name="defaultCommissionPercent" type="number" min="0" max="100" step="0.01" value="${esc(s.defaultCommissionPercent||0)}"></label><label class="check" style="align-self:end;padding-bottom:12px"><input name="requiresRoom" type="checkbox" ${s.requiresRoom!==false?'checked':''}> Requiere cabina</label><label class="field span-2">Descripción<textarea name="description" maxlength="600">${esc(s.description||'')}</textarea></label></div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Guardar</button></div></form>`);
  }
  function modalEmployee(employee=null){
    const e=employee||{}; showModal(employee?'Editar profesional':'Nuevo profesional',`<form id="employeeForm"><input type="hidden" name="id" value="${esc(e.id||'')}"><div class="form-grid"><label class="field">Nombre completo<input name="fullName" required maxlength="150" value="${esc(e.fullName||'')}"></label><label class="field">Especialidad<input name="specialty" maxlength="120" value="${esc(e.specialty||'')}"></label><label class="field">Teléfono<input name="phone" maxlength="30" value="${esc(e.phone||'')}"></label><label class="field">Correo<input name="email" type="email" maxlength="150" value="${esc(e.email||'')}"></label><label class="field">Sucursal<select name="branchId">${db.branches.filter(b=>b.isActive).map(b=>`<option value="${b.id}" ${String(b.id)===String(e.branchId||1)?'selected':''}>${esc(b.name)}</option>`).join('')}</select></label><label class="field">Comisión %<input name="commissionPercent" type="number" min="0" max="100" step="0.01" value="${esc(e.commissionPercent||0)}"></label></div><fieldset style="border:0;padding:0;margin:14px 0"><legend style="font-weight:800;font-size:.86rem;margin-bottom:8px">Servicios habilitados</legend><div class="chips">${db.services.filter(s=>s.isActive).map(s=>`<label class="chip"><input type="checkbox" name="serviceIds" value="${s.id}" ${(e.serviceIds||[]).includes(s.id)?'checked':''}> ${esc(s.name)}</label>`).join('')}</div></fieldset><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Guardar</button></div></form>`);
  }
  function modalProduct(product=null){
    const p=product||{}; showModal(product?'Editar producto':'Nuevo producto',`<form id="productForm"><input type="hidden" name="id" value="${esc(p.id||'')}"><div class="form-grid cols-3"><label class="field">Producto<input name="name" maxlength="140" required value="${esc(p.name||'')}"></label><label class="field">Categoría<select name="productCategoryId">${db.productCategories.filter(c=>c.isActive).map(c=>`<option value="${c.id}" ${String(c.id)===String(p.productCategoryId||1)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label class="field">SKU<input name="sku" maxlength="80" value="${esc(p.sku||'')}"></label><label class="field">Código de barras<input name="barcode" maxlength="80" value="${esc(p.barcode||'')}"></label><label class="field">Costo<input name="cost" type="number" min="0" step="0.01" value="${esc(p.cost||0)}"></label><label class="field">Precio venta<input name="salePrice" type="number" min="0" step="0.01" value="${esc(p.salePrice||0)}"></label><label class="field">Stock<input name="stock" type="number" step="0.01" value="${esc(p.stock||0)}"></label><label class="field">Stock mínimo<input name="minimumStock" type="number" min="0" step="0.01" value="${esc(p.minimumStock||0)}"></label></div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Guardar</button></div></form>`);
  }
  function modalStock(id){ const p=byId(db.products,id); if(!p)return; showModal(`Ajustar stock · ${p.name}`,`<form id="stockForm"><input type="hidden" name="productId" value="${p.id}"><div class="report-note">Stock actual: <strong>${p.stock}</strong></div><div class="form-grid" style="margin-top:14px"><label class="field">Tipo<select name="type"><option value="Purchase">Compra / entrada</option><option value="InternalUse">Uso interno</option><option value="AdjustmentIn">Ajuste entrada</option><option value="AdjustmentOut">Ajuste salida</option><option value="Return">Devolución</option></select></label><label class="field">Cantidad<input name="quantity" type="number" min="0.01" step="0.01" required></label><label class="field span-2">Notas<textarea name="notes"></textarea></label></div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Registrar movimiento</button></div></form>`); }
  function modalMovements(){ const list=[...db.movements].sort((a,b)=>new Date(b.occurredAt)-new Date(a.occurredAt)).slice(0,100); showModal('Movimientos de inventario',`<div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Producto</th><th>Tipo</th><th>Cantidad</th><th>Notas</th></tr></thead><tbody>${list.map(m=>`<tr><td>${fmtDateTime(m.occurredAt)}</td><td>${esc(byId(db.products,m.productId)?.name||'—')}</td><td>${esc(m.type)}</td><td><strong>${Number(m.quantity)>0?'+':''}${m.quantity}</strong></td><td>${esc(m.notes||'')}</td></tr>`).join('')}</tbody></table></div>`,true); }
  function modalAppointmentDetail(id){ const a=byId(db.appointments,id);if(!a)return;const c=byId(db.clients,a.clientId),e=byId(db.employees,a.employeeId),r=byId(db.rooms,a.roomId); showModal(`Reserva #${a.id}`,`<div class="grid-2"><div><div class="kv"><span>Cliente</span><strong>${esc(c?.fullName||'—')}</strong></div><div class="kv"><span>Horario</span><strong>${fmtDateTime(a.startAt)} – ${fmtTime(a.endAt)}</strong></div><div class="kv"><span>Profesional</span><strong>${esc(e?.fullName||'—')}</strong></div><div class="kv"><span>Cabina</span><strong>${esc(r?.name||'—')}</strong></div></div><div><div class="kv"><span>Estado</span><strong>${statusLabel(a.status)}</strong></div><div class="kv"><span>Origen</span><strong>${sourceLabel(a.source)}</strong></div><div class="kv"><span>Pago</span><strong>${statusLabel(a.paymentStatus)}</strong></div><div class="kv"><span>Total</span><strong>${money(a.total)}</strong></div></div></div><h3 style="margin-top:18px">Servicios</h3><ul class="clean-list">${(a.items||[]).map(i=>`<li><span>${esc(byId(db.services,i.spaServiceId)?.name||'—')} · ${i.durationMinutes} min</span><strong>${money(i.unitPrice*i.quantity)}</strong></li>`).join('')}</ul>${a.notes?`<div class="report-note" style="margin-top:14px"><strong>Notas:</strong> ${esc(a.notes)}</div>`:''}<div class="form-actions">${canCash()&&a.paymentStatus!=='Paid'&&!['Cancelled','NoShow'].includes(a.status)?`<button class="btn good" data-action="appointment-pay" data-id="${a.id}">Cobrar</button>`:''}${canFrontDesk()&&!['Completed','Cancelled','NoShow'].includes(a.status)?`<button class="btn danger" data-action="appointment-cancel" data-id="${a.id}">Cancelar cita</button>`:''}<button class="btn" data-action="close-modal">Cerrar</button></div>`); }
  function modalPayment(id){ const a=byId(db.appointments,id);if(!a)return;const paid=db.payments.filter(p=>String(p.appointmentId)===String(id)&&p.status==='Paid').reduce((s,p)=>s+Number(p.amount),0);const due=Math.max(0,Number(a.total)-paid);showModal(`Cobrar reserva #${a.id}`,`<form id="paymentForm"><input type="hidden" name="appointmentId" value="${a.id}"><div class="report-note">Total ${money(a.total)} · Pagado ${money(paid)} · Pendiente <strong>${money(due)}</strong></div><div class="form-grid" style="margin-top:14px"><label class="field">Monto<input name="amount" type="number" min="0.01" step="0.01" max="${due}" value="${due}" required></label><label class="field">Método<select name="method">${['Cash','Card','Qr','Transfer','GiftCard','Other'].map(m=>`<option value="${m}">${methodLabel(m)}</option>`).join('')}</select></label><label class="field span-2">Referencia<input name="reference" maxlength="150"></label></div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Registrar pago</button></div></form>`); }

  let saleCart=[];
  function modalSale(){ saleCart=[]; showModal('Nueva venta',saleFormHtml(),true); }
  function saleFormHtml(){ return `<form id="saleForm"><div class="form-grid"><label class="field">Cliente<select name="clientId"><option value="">Cliente general</option>${db.clients.filter(c=>c.isActive).map(c=>`<option value="${c.id}">${esc(c.fullName)}</option>`).join('')}</select></label><label class="field">Método de pago<select name="method">${['Cash','Card','Qr','Transfer','GiftCard','Other'].map(m=>`<option value="${m}">${methodLabel(m)}</option>`).join('')}</select></label></div><div class="filter-bar" style="margin-top:14px"><label class="field"><span>Tipo</span><select id="saleItemType"><option value="product">Producto</option><option value="service">Servicio</option></select></label><label class="field search"><span>Ítem</span><select id="saleItemId">${db.products.filter(p=>p.isActive).map(p=>`<option value="${p.id}">${esc(p.name)} · ${money(p.salePrice)}</option>`).join('')}</select></label><label class="field"><span>Cantidad</span><input id="saleQty" type="number" min="1" step="1" value="1"></label><button class="btn" type="button" data-action="sale-add-item">Agregar</button></div><div id="saleCartArea">${saleCartHtml()}</div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit" ${saleCart.length?'':'disabled'}>Cobrar venta</button></div></form>`; }
  function saleCartHtml(){ const total=saleCart.reduce((s,i)=>s+i.unitPrice*i.quantity,0); return saleCart.length?`<div class="table-wrap"><table><thead><tr><th>Ítem</th><th>Cant.</th><th>Unitario</th><th>Total</th><th></th></tr></thead><tbody>${saleCart.map((i,idx)=>`<tr><td>${esc(i.name)}</td><td>${i.quantity}</td><td>${money(i.unitPrice)}</td><td>${money(i.unitPrice*i.quantity)}</td><td><button class="btn sm danger" type="button" data-action="sale-remove-item" data-index="${idx}">×</button></td></tr>`).join('')}</tbody></table></div><div style="text-align:right;font-size:1.2rem;font-weight:900;margin-top:12px">Total: ${money(total)}</div>`:`<div class="empty-state">Agrega al menos un producto o servicio.</div>`; }
  function refreshSaleModal(){ const area=document.getElementById('saleCartArea'); if(area) area.innerHTML=saleCartHtml(); const submit=document.querySelector('#saleForm button[type="submit"]'); if(submit) submit.disabled=!saleCart.length; }
  function modalSaleDetail(id){ const s=byId(db.sales,id); if(!s)return; showModal(`Venta #${s.id}`,`<div class="kv"><span>Fecha</span><strong>${fmtDateTime(s.soldAt)}</strong></div><div class="kv"><span>Cliente</span><strong>${esc(byId(db.clients,s.clientId)?.fullName||'Cliente general')}</strong></div><h3 style="margin-top:16px">Detalle</h3><ul class="clean-list">${(s.items||[]).map(i=>{const name=i.productId?byId(db.products,i.productId)?.name:byId(db.services,i.spaServiceId)?.name;return `<li><span>${esc(name||'Ítem')} × ${i.quantity}</span><strong>${money(i.lineTotal)}</strong></li>`}).join('')}</ul><div style="text-align:right;font-size:1.25rem;font-weight:900;margin-top:14px">${money(s.total)}</div>`); }
  function modalExpense(){ showModal('Registrar gasto',`<form id="expenseForm"><div class="form-grid"><label class="field">Concepto<input name="concept" maxlength="140" required></label><label class="field">Monto<input name="amount" type="number" min="0.01" step="0.01" required></label><label class="field">Fecha y hora<input name="expenseAt" type="datetime-local" value="${dateTimeLocal(new Date())}" required></label><label class="field span-2">Notas<textarea name="notes" maxlength="300"></textarea></label></div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Guardar gasto</button></div></form>`); }
  function modalMembership(){ showModal('Asignar membresía',`<form id="membershipForm"><div class="form-grid"><label class="field">Cliente<select name="clientId">${db.clients.filter(c=>c.isActive).map(c=>`<option value="${c.id}">${esc(c.fullName)}</option>`).join('')}</select></label><label class="field">Plan<select name="membershipPlanId">${db.membershipPlans.filter(p=>p.isActive!==false).map(p=>`<option value="${p.id}">${esc(p.name)} · ${money(p.price)}</option>`).join('')}</select></label><label class="field">Fecha inicio<input name="startDate" type="date" value="${todayISO()}" required></label></div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Asignar</button></div></form>`); }
  function modalGiftCard(){ showModal('Nueva gift card',`<form id="giftCardForm"><div class="form-grid"><label class="field">Código<input name="code" maxlength="50" required value="SPA-GIFT-${String(nextId(db.giftCards)).padStart(3,'0')}"></label><label class="field">Saldo inicial<input name="initialBalance" type="number" min="1" step="0.01" required></label><label class="field">Vencimiento<input name="expiresOn" type="date" value="${dateAddISO(90)}"></label><label class="field">Cliente<select name="assignedClientId"><option value="">Sin asignar</option>${db.clients.filter(c=>c.isActive).map(c=>`<option value="${c.id}">${esc(c.fullName)}</option>`).join('')}</select></label></div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Crear gift card</button></div></form>`); }
  function modalPlan(){ showModal('Nuevo plan de membresía',`<form id="planForm"><div class="form-grid"><label class="field">Nombre<input name="name" maxlength="120" required></label><label class="field">Duración (días)<input name="durationDays" type="number" min="1" value="30" required></label><label class="field">Precio<input name="price" type="number" min="0" step="0.01" required></label><label class="field">Descuento servicios %<input name="serviceDiscountPercent" type="number" min="0" max="100" step="0.01" value="0"></label><label class="field span-2">Descripción<textarea name="description" maxlength="500"></textarea></label></div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Guardar plan</button></div></form>`); }
  function modalBranch(branch=null){ const b=branch||{}; showModal(branch?'Editar sucursal':'Nueva sucursal',`<form id="branchForm"><input type="hidden" name="id" value="${esc(b.id||'')}"><div class="form-grid"><label class="field">Nombre<input name="name" required value="${esc(b.name||'')}"></label><label class="field">Teléfono<input name="phone" value="${esc(b.phone||'')}"></label><label class="field span-2">Dirección<textarea name="address">${esc(b.address||'')}</textarea></label></div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Guardar</button></div></form>`); }
  function modalRoom(room=null){ const r=room||{}; showModal(room?'Editar cabina':'Nueva cabina',`<form id="roomForm"><input type="hidden" name="id" value="${esc(r.id||'')}"><div class="form-grid"><label class="field">Nombre<input name="name" required value="${esc(r.name||'')}"></label><label class="field">Sucursal<select name="branchId">${db.branches.filter(b=>b.isActive!==false).map(b=>`<option value="${b.id}" ${String(b.id)===String(r.branchId||1)?'selected':''}>${esc(b.name)}</option>`).join('')}</select></label><label class="field">Capacidad<input name="capacity" type="number" min="1" value="${esc(r.capacity||1)}"></label><label class="field span-2">Descripción<textarea name="description">${esc(r.description||'')}</textarea></label></div><div class="form-actions"><button class="btn" type="button" data-action="close-modal">Cancelar</button><button class="btn primary" type="submit">Guardar</button></div></form>`); }

  function nextAppointmentStatus(status){ return ({Pending:'Confirmed',Confirmed:'CheckedIn',CheckedIn:'InService',InService:'Completed'})[status]||status; }
  function advanceAppointment(id){ const a=byId(db.appointments,id);if(!a)return; const next=nextAppointmentStatus(a.status); if(next===a.status){toast('La reserva ya no tiene un siguiente estado.');return;} a.status=next; if(next==='Completed'){const c=byId(db.clients,a.clientId);if(c){c.lastVisitAt=a.endAt;c.loyaltyPoints=Number(c.loyaltyPoints||0)+Math.floor(Number(a.total||0)/10);}} saveDb();audit('Status','Appointment',a.id,`Estado: ${next}`);toast(`Reserva marcada como ${statusLabel(next)}.`,'good');renderShell(); }

  function serializeForm(form){ return Object.fromEntries(new FormData(form).entries()); }

  document.addEventListener('submit', e => {
    const f=e.target; if(!(f instanceof HTMLFormElement)) return;
    if(['loginForm','publicBookingForm','appointmentForm','clientForm','serviceForm','employeeForm','productForm','stockForm','paymentForm','saleForm','expenseForm','membershipForm','giftCardForm','planForm','settingsForm','branchForm','roomForm'].includes(f.id)) e.preventDefault(); else return;
    try{
      const d=serializeForm(f);
      if(f.id==='loginForm'){
        const u=db.users.find(x=>x.active&&x.email.toLowerCase()===String(d.email).trim().toLowerCase()&&x.password===d.password); if(!u) throw new Error('Correo o contraseña incorrectos.'); loginUser(u); render(); return;
      }
      if(f.id==='publicBookingForm'){
        if(!f.contactConsent.checked) throw new Error('Debes autorizar el contacto para confirmar la reserva.'); let c=db.clients.find(x=>x.phone===d.phone&&x.isActive); if(!c){c={id:nextId(db.clients),spaBusinessId:1,fullName:d.fullName,phone:d.phone,email:d.email||'',birthDate:null,notes:'',allergies:'',contraindications:'',marketingConsent:false,treatmentConsent:false,loyaltyPoints:0,lastVisitAt:null,createdAt:new Date().toISOString(),isActive:true};db.clients.push(c);}else{c.fullName=d.fullName;if(d.email)c.email=d.email;} const a=createAppointmentFromForm({clientId:c.id,serviceId:d.serviceId,employeeId:d.employeeId,roomId:null,startAt:d.startAt,source:'Web',notes:d.notes},true); sessionStorage.setItem('spaflow_last_booking',a.id); saveDb(); location.hash='#booking-success'; return;
      }
      if(f.id==='appointmentForm'){ createAppointmentFromForm(d,false); closeModal();toast('Reserva creada correctamente.','good');navigate('appointments');render();return; }
      if(f.id==='clientForm'){ let c=d.id?byId(db.clients,d.id):null; if(!c){c={id:nextId(db.clients),spaBusinessId:1,loyaltyPoints:0,lastVisitAt:null,createdAt:new Date().toISOString(),isActive:true};db.clients.push(c);} Object.assign(c,{fullName:d.fullName,phone:d.phone,email:d.email,birthDate:d.birthDate||null,allergies:d.allergies,contraindications:d.contraindications,notes:d.notes,treatmentConsent:f.treatmentConsent.checked,marketingConsent:f.marketingConsent.checked});saveDb();audit(d.id?'Update':'Create','Client',c.id,c.fullName);closeModal();toast('Cliente guardado.','good');renderShell();return; }
      if(f.id==='serviceForm'){ let s=d.id?byId(db.services,d.id):null;if(!s){s={id:nextId(db.services),spaBusinessId:1,isActive:true};db.services.push(s);}Object.assign(s,{name:d.name,serviceCategoryId:Number(d.serviceCategoryId),durationMinutes:Number(d.durationMinutes),price:Number(d.price),defaultCommissionPercent:Number(d.defaultCommissionPercent||0),requiresRoom:f.requiresRoom.checked,description:d.description});saveDb();audit(d.id?'Update':'Create','SpaService',s.id,s.name);closeModal();toast('Servicio guardado.','good');renderShell();return; }
      if(f.id==='employeeForm'){ let x=d.id?byId(db.employees,d.id):null;if(!x){x={id:nextId(db.employees),spaBusinessId:1,isActive:true};db.employees.push(x);}const ids=[...f.querySelectorAll('input[name="serviceIds"]:checked')].map(x=>Number(x.value));Object.assign(x,{fullName:d.fullName,specialty:d.specialty,phone:d.phone,email:d.email,branchId:Number(d.branchId),commissionPercent:Number(d.commissionPercent||0),serviceIds:ids});saveDb();audit(d.id?'Update':'Create','Employee',x.id,x.fullName);closeModal();toast('Profesional guardado.','good');renderShell();return; }
      if(f.id==='productForm'){ let p=d.id?byId(db.products,d.id):null;const wasNew=!p;if(!p){p={id:nextId(db.products),spaBusinessId:1,isActive:true};db.products.push(p);}Object.assign(p,{name:d.name,productCategoryId:Number(d.productCategoryId),sku:d.sku,barcode:d.barcode,cost:Number(d.cost||0),salePrice:Number(d.salePrice||0),stock:Number(d.stock||0),minimumStock:Number(d.minimumStock||0)});saveDb();audit(wasNew?'Create':'Update','Product',p.id,p.name);closeModal();toast('Producto guardado.','good');renderShell();return; }
      if(f.id==='stockForm'){ const p=byId(db.products,d.productId);if(!p)throw new Error('Producto inválido.');let q=Math.abs(Number(d.quantity));if(['InternalUse','AdjustmentOut','Sale'].includes(d.type)) q=-q;if(Number(p.stock)+q<0) throw new Error('El movimiento dejaría stock negativo.');p.stock=Number(p.stock)+q;const m={id:nextId(db.movements),spaBusinessId:1,branchId:1,productId:p.id,type:d.type,quantity:q,occurredAt:new Date().toISOString(),notes:d.notes};db.movements.push(m);saveDb();audit('Stock','Product',p.id,`${d.type}: ${q}`);closeModal();toast('Movimiento registrado.','good');renderShell();return; }
      if(f.id==='paymentForm'){ const a=byId(db.appointments,d.appointmentId);if(!a)throw new Error('Reserva inválida.');const amt=Number(d.amount);if(!(amt>0))throw new Error('Monto inválido.');db.payments.push({id:nextId(db.payments),spaBusinessId:1,appointmentId:a.id,saleId:null,clientId:a.clientId,method:d.method,status:'Paid',amount:amt,reference:d.reference||'',paidAt:new Date().toISOString()});const totalPaid=db.payments.filter(p=>String(p.appointmentId)===String(a.id)&&p.status==='Paid').reduce((s,p)=>s+Number(p.amount),0);a.paymentStatus=totalPaid>=Number(a.total)-.001?'Paid':'Partial';saveDb();audit('Payment','Appointment',a.id,`${methodLabel(d.method)} ${money(amt)}`);closeModal();toast('Pago registrado.','good');renderShell();return; }
      if(f.id==='saleForm'){ if(!saleCart.length)throw new Error('Agrega al menos un ítem.');for(const i of saleCart.filter(x=>x.productId)){const p=byId(db.products,i.productId);if(!p||Number(p.stock)<i.quantity)throw new Error(`Stock insuficiente para ${i.name}.`);}const total=saleCart.reduce((s,i)=>s+i.unitPrice*i.quantity,0);const sale={id:nextId(db.sales),spaBusinessId:1,branchId:1,clientId:d.clientId?Number(d.clientId):null,soldAt:new Date().toISOString(),subtotal:total,discount:0,total,items:saleCart.map((i,k)=>({id:Date.now()+k,productId:i.productId||null,spaServiceId:i.spaServiceId||null,quantity:i.quantity,unitPrice:i.unitPrice,lineTotal:i.unitPrice*i.quantity}))};db.sales.push(sale);saleCart.filter(x=>x.productId).forEach(i=>{const p=byId(db.products,i.productId);p.stock=Number(p.stock)-i.quantity;db.movements.push({id:nextId(db.movements),spaBusinessId:1,branchId:1,productId:p.id,type:'Sale',quantity:-i.quantity,occurredAt:new Date().toISOString(),notes:`Venta #${sale.id}`});});db.payments.push({id:nextId(db.payments),spaBusinessId:1,appointmentId:null,saleId:sale.id,clientId:sale.clientId,method:d.method,status:'Paid',amount:total,reference:'',paidAt:new Date().toISOString()});saveDb();audit('Create','Sale',sale.id,money(total));closeModal();toast('Venta registrada y cobrada.','good');renderShell();return; }
      if(f.id==='expenseForm'){const x={id:nextId(db.expenses),spaBusinessId:1,branchId:1,concept:d.concept,amount:Number(d.amount),expenseAt:d.expenseAt,notes:d.notes};db.expenses.push(x);saveDb();audit('Create','Expense',x.id,`${x.concept}: ${money(x.amount)}`);closeModal();toast('Gasto registrado.','good');renderShell();return;}
      if(f.id==='membershipForm'){const plan=byId(db.membershipPlans,d.membershipPlanId);if(!plan)throw new Error('Plan inválido.');const start=new Date(d.startDate+'T00:00');const end=new Date(start);end.setDate(end.getDate()+Number(plan.durationDays));const m={id:nextId(db.clientMemberships),spaBusinessId:1,clientId:Number(d.clientId),membershipPlanId:Number(d.membershipPlanId),startDate:d.startDate,endDate:`${end.getFullYear()}-${pad(end.getMonth()+1)}-${pad(end.getDate())}`,isActive:true};db.clientMemberships.push(m);saveDb();audit('Create','ClientMembership',m.id,plan.name);closeModal();toast('Membresía asignada.','good');renderShell();return;}
      if(f.id==='giftCardForm'){if(db.giftCards.some(g=>g.code.toLowerCase()===d.code.toLowerCase()))throw new Error('El código de gift card ya existe.');const g={id:nextId(db.giftCards),spaBusinessId:1,code:d.code,initialBalance:Number(d.initialBalance),currentBalance:Number(d.initialBalance),expiresOn:d.expiresOn||null,assignedClientId:d.assignedClientId?Number(d.assignedClientId):null,isActive:true};db.giftCards.push(g);saveDb();audit('Create','GiftCard',g.id,g.code);closeModal();toast('Gift card creada.','good');renderShell();return;}
      if(f.id==='planForm'){const p={id:nextId(db.membershipPlans),spaBusinessId:1,name:d.name,description:d.description,durationDays:Number(d.durationDays),price:Number(d.price),serviceDiscountPercent:Number(d.serviceDiscountPercent||0),isActive:true};db.membershipPlans.push(p);saveDb();audit('Create','MembershipPlan',p.id,p.name);closeModal();toast('Plan creado.','good');renderShell();return;}
      if(f.id==='settingsForm'){Object.assign(db.business,{name:d.name,legalName:d.legalName,phone:d.phone,email:d.email,currency:d.currency,address:d.address,timeZoneId:d.timeZoneId});saveDb();audit('Update','SpaBusiness',db.business.id,'Configuración actualizada');toast('Configuración guardada.','good');renderShell();return;}
      if(f.id==='branchForm'){let b=d.id?byId(db.branches,d.id):null;if(!b){b={id:nextId(db.branches),spaBusinessId:1,isActive:true};db.branches.push(b);}Object.assign(b,{name:d.name,phone:d.phone,address:d.address});saveDb();audit(d.id?'Update':'Create','Branch',b.id,b.name);closeModal();toast('Sucursal guardada.','good');renderShell();return;}
      if(f.id==='roomForm'){let r=d.id?byId(db.rooms,d.id):null;if(!r){r={id:nextId(db.rooms),spaBusinessId:1,isActive:true};db.rooms.push(r);}Object.assign(r,{name:d.name,branchId:Number(d.branchId),capacity:Number(d.capacity||1),description:d.description});saveDb();audit(d.id?'Update':'Create','Room',r.id,r.name);closeModal();toast('Cabina guardada.','good');renderShell();return;}
    }catch(err){ const box=document.getElementById('modalValidation'); if(box)box.innerHTML=`<div class="validation-box">${esc(err.message||err)}</div>`; else toast(err.message||String(err),'danger'); }
  });

  document.addEventListener('click', e => {
    const nav=e.target.closest('[data-nav]'); if(nav){e.preventDefault();sidebarOpen=false;navigate(nav.dataset.nav);return;}
    const el=e.target.closest('[data-action]'); if(!el)return; const action=el.dataset.action,id=el.dataset.id;
    if(action==='close-modal'){ if(e.target.classList.contains('modal-backdrop')||el.classList.contains('modal-close')||el.dataset.action==='close-modal') closeModal(); }
    else if(action==='logout') logout();
    else if(action==='toggle-sidebar'){sidebarOpen=!sidebarOpen;document.getElementById('sidebar')?.classList.toggle('open',sidebarOpen);}
    else if(action==='quick-book') modalAppointment();
    else if(action==='apply-appointment-filter'){const d=document.getElementById('appointmentDateFilter').value,s=document.getElementById('appointmentStatusFilter').value;location.hash=`#appointments?date=${encodeURIComponent(d)}${s?`&status=${encodeURIComponent(s)}`:''}`;}
    else if(action==='appointment-detail') modalAppointmentDetail(id);
    else if(action==='appointment-next') advanceAppointment(id);
    else if(action==='appointment-pay') modalPayment(id);
    else if(action==='appointment-cancel'){const a=byId(db.appointments,id);if(a&&confirm('¿Cancelar esta reserva?')){a.status='Cancelled';saveDb();audit('Status','Appointment',a.id,'Cancelada');closeModal();toast('Reserva cancelada.');renderShell();}}
    else if(action==='new-client') modalClient();
    else if(action==='edit-client') modalClient(byId(db.clients,id));
    else if(action==='client-detail') modalClientDetail(id);
    else if(action==='search-client'){const q=document.getElementById('clientSearch').value;location.hash=`#clients?q=${encodeURIComponent(q)}`;}
    else if(action==='new-service') modalService();
    else if(action==='edit-service') modalService(byId(db.services,id));
    else if(action==='new-employee') modalEmployee();
    else if(action==='edit-employee') modalEmployee(byId(db.employees,id));
    else if(action==='new-product') modalProduct();
    else if(action==='edit-product') modalProduct(byId(db.products,id));
    else if(action==='stock-adjust') modalStock(id);
    else if(action==='inventory-movements') modalMovements();
    else if(action==='new-sale') modalSale();
    else if(action==='sale-add-item') {const type=document.getElementById('saleItemType').value,idv=Number(document.getElementById('saleItemId').value),qty=Math.max(1,Number(document.getElementById('saleQty').value||1));const src=type==='product'?byId(db.products,idv):byId(db.services,idv);if(!src)return;const item=type==='product'?{productId:src.id,name:src.name,quantity:qty,unitPrice:Number(src.salePrice)}:{spaServiceId:src.id,name:src.name,quantity:qty,unitPrice:Number(src.price)};const existing=saleCart.find(x=>(x.productId&&x.productId===item.productId)||(x.spaServiceId&&x.spaServiceId===item.spaServiceId));if(existing)existing.quantity+=qty;else saleCart.push(item);refreshSaleModal();}
    else if(action==='sale-remove-item'){saleCart.splice(Number(el.dataset.index),1);refreshSaleModal();}
    else if(action==='sale-detail') modalSaleDetail(id);
    else if(action==='new-expense') modalExpense();
    else if(action==='delete-expense'){if(confirm('¿Eliminar este gasto?')){const i=db.expenses.findIndex(x=>String(x.id)===String(id));if(i>=0){const x=db.expenses.splice(i,1)[0];saveDb();audit('Delete','Expense',x.id,x.concept);renderShell();}}}
    else if(action==='new-membership') modalMembership();
    else if(action==='new-giftcard') modalGiftCard();
    else if(action==='new-plan') modalPlan();
    else if(action==='apply-report-filter'){const from=document.getElementById('reportFrom').value,to=document.getElementById('reportTo').value;location.hash=`#reports?from=${from}&to=${to}`;}
    else if(action==='new-branch') modalBranch();
    else if(action==='edit-branch') modalBranch(byId(db.branches,id));
    else if(action==='new-room') modalRoom();
    else if(action==='edit-room') modalRoom(byId(db.rooms,id));
    else if(action==='reset-data'){if(confirm('Esto eliminará los cambios locales y restaurará los datos demo. ¿Continuar?')) resetDb();}
    else if(action==='export-data') exportData();
  });

  document.addEventListener('change', e=>{
    if(e.target.id==='saleItemType'){const type=e.target.value,sel=document.getElementById('saleItemId');if(sel)sel.innerHTML=(type==='product'?db.products.filter(p=>p.isActive).map(p=>`<option value="${p.id}">${esc(p.name)} · ${money(p.salePrice)}</option>`):db.services.filter(s=>s.isActive).map(s=>`<option value="${s.id}">${esc(s.name)} · ${money(s.price)}</option>`)).join('');}
    if(e.target.id==='importFile') importData(e.target.files?.[0]);
  });

  window.addEventListener('hashchange',()=>{sidebarOpen=false;render();});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});

  function exportData(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`SpaFlow-backup-${todayISO()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500);audit('Export','Database','local','Respaldo JSON exportado');toast('Respaldo JSON exportado.','good');}
  function importData(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data.business||!Array.isArray(data.clients)||!Array.isArray(data.appointments))throw new Error('El archivo no tiene la estructura de SpaFlow.');db=data;saveDb();audit('Import','Database','local','Respaldo JSON importado');toast('Datos importados.','good');renderShell();}catch(err){toast(err.message||'No se pudo importar.','danger');}};reader.readAsText(file);}

  (async()=>{ await loadDb(); render(); })();
})();
